name: compile-latex
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: docker://blang/latex:latest
    steps:
      - name: Install latex stuff 
        run: |
          sudo ln -snf /usr/share/zoneinfo/Etc/UTC /etc/localtime \
          && sudo echo "Etc/UTC" > /etc/timezone \
          && sudo apt-get update \
          && sudo apt-get upgrade -y \
          && sudo apt-get install texlive-latex-base texlive-latex-extra texlive-fonts-recommended xzdec -y \
          && sudo rm -rf /var/lib/apt/lists/*

      - name: Compile tex into pdf
        run: |
          pdflatex -output-directory assets/resume assets/resume/ChristosMitropoulos - Resume.tex
      - run: echo "🍏 This job's status is ${{ job.status }}."
