name: build-resume

on:
  push:
    paths:
      - 'assets/resume/*tex'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-resume:
    name: "pull docker image and build resume from latex"
    runs-on: ubuntu-latest
   
    steps:
       
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Pull image from DockerHub
      run: docker pull cmitropoulos/latex:latest
    
    - name: checkout action
      uses: actions/checkout@v1
    - name: create pdf
      run: docker run  -v "$(pwd)"/assets/resume/:/data/assets/resume cmitropoulos/latex:latest   pdflatex -output-directory /data/assets/resume /data/assets/resume/ChristosMitropoulos\ -\ Resume.tex
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "autoupdating resume" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    - name: Results 
      run: echo "🍏 This job's status is ${{ job.status }}."
