name: compile-latex
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - name: Install latex stuff
        run: |
          apt-get update \
          && apt-get upgrade -y \
          && apt-get install texlive-latex-base texlive-latex-extra texlive-fonts-recommended xzdec -y \
          && rm -rf /var/lib/apt/lists/*

      - name: Compile tex into pdf
        run: |
          pdflatex -output-directory assets/resume assets/resume/ChristosMitropoulos - Resume.tex
      - run: echo "🍏 This job's status is ${{ job.status }}."
