name: ci
on:
  push:
    branches:
      - 'master'
jobs:
    compile-latex:
      runs-on: ubuntu-20.04
      steps:
        -
          name: Checkout
          uses: actions/checkout@v2
        - 
          name: Login to Docker Hub
          uses: docker/blang/latex:ubuntu
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        - name: Compile tex into pdf
          run: |
            pdflatex -output-directory assets/resume assets/resume/ChristosMitropoulos - Resume.tex
        - run: echo "🍏 This job's status is ${{ job.status }}."
