name: compile-latex
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: blang/latex:ubuntu
    steps:
      - name: Compile tex into pdf
        run: |
          pdflatex -output-directory assets/resume assets/resume/ChristosMitropoulos - Resume.tex
      - run: echo "🍏 This job's status is ${{ job.status }}."
