name: build-resume

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-resume:
    name: "pull docker image and build resume from latex"
    runs-on: ubuntu-latest
   
    steps:
       
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Pull image from DockerHub
      run: docker pull cmitropoulos/latex:latest

    - name: Run image in container
      run: docker run -it  -v "$(pwd)"/assets/resume/:/data/assets/resume cmitropoulos/latex:latest /bin/bash
    
    - name: Compile latex
      run: pdflatex -output-directory assets/resume assets/resume/ChristosMitropoulos - Resume.tex

    - name: Results 
      run: echo "🍏 This job's status is ${{ job.status }}."
